### ISSUE TITLE
%20

### ISSUE THREAD

**Issue by Velocet** [Velocet/PowerShell#3]

**Comment by Velocet** [comment]
GIT SUCKS BIG TIME!

**Comment by Epooch** [comment]
So what makes git suck so much?

**Comment by Sjneugent** [comment]
Fucking normies, REEEEEEEEEEEEEEEEEEEEE

**Comment by Velocet** [comment]
@Epooch well.. as said: it is just way too complicated and not possible to normally automanage some things... there is no real good GUI (yeah.. i know.. use cmd ..)
i want a switch that a directory acts like a dropbox dir: JUST ADD EVERY FUCKING FILE. is it really that complicated? why the fuck do i have to do this myself?
and forking other projects inside my own .. good lord .. and when you are working with branches .. OMFG .. this is really nothing you wanna deal with.

Git just sucks: if a CVS lets you delete files with a checkin that are not checked in .. well..

**Comment by InstanceOfMichael** [comment]
> Git just sucks: if a CVS lets you delete files with a checkin that are not checked in .. well..

Interesting. I've never experienced this issue with a CVS. Have you tried Walgreen's?

**Comment by paulcjohnson** [comment]
does not need fixing. your an idiot! don;t post here again.

**Comment by DwordPtr** [comment]
With git you're trading ease of use for power. That doesn't necessarily mean it sucks. If you want a lessened complexity tax just use mercurial or subversion.

Btw if any of you hate some of the less intuitive parts of git there's always gitless http://gitless.com/  

And lastly most ides have a way for you to use git without shooting yourself in the foot.  (visual studio, intellij, etc).

But you know it's bad and no amount of responsibility will counteract the git sucks meme.

**Comment by DwordPtr** [comment]
Resonability not responsibility. Phone auto complete sucks.

**Comment by ProfessorTom** [comment]
Have you tried [RCS](https://en.wikipedia.org/wiki/Revision_Control_System)?
